### ISSUE TITLE
residuals of the sum of squares doesn't work for Seurat object

### ISSUE THREAD

**Issue by MirDom** [MarcElosua/SPOTlight#101]
Hi, 
i am following your tutorial on https://bioconductor.org/packages/devel/bioc/vignettes/SPOTlight/inst/doc/SPOTlight_kidney.html#loading-the-data to analyze data saved as Seurat object of spatial transcriptomics data. Everything works up untill the last step 4.5 Residuals.
When trying to run the command (where B2 is my seurat object, instead of spe as in tutorial):

B2$res_ss <- res[[2]][colnames(B2)]
xy <- spatialCoords(spe)
B2$x <- xy[, 1]
B2$y <- xy[, 2]
ggcells(B2, aes(x, y, color = res_ss)) +
    geom_point() +
    scale_color_viridis_c() +
    coord_fixed() +
    theme_bw()

it gives the following error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘spatialCoords’ for signature ‘"Seurat"’.

I assume it stems inherently from Seurat object features because when I run the same command for spe object as in the tutorial it works fine. Am I correct in my assumption? Have anyone tried this command on seurat object  of spatial transcriptomics data?

**Comment by MarcElosua** [comment]
Hi @MirDom 

Thank you very much for your interest in SPOTlight!

Your issue here is that you are trying to use the `ggcells()` function which is part of the [scater](https://rdrr.io/bioc/scater/man/ggsce.html) package. This functino doesn't accept Seurat objects as an input, hence the error:

```
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘spatialCoords’ for signature ‘"Seurat"’.
```

For Seurat I suggest using the standards FeaturePlot() function to plot it,
Hope this helps,
Marc

**Comment by Han117** [comment]
Hi Marc,
I found datas (allen_cortex_dwn.rds、markers_anterior.RDS、spotlight_ls_anterior.RDS、tissue_lowres_image.png) in your SPOTlight-spotlight-0.1.7 project on github, but the posterior data and its spatial slices are missing.

I am looking forward to your posterior data and its spatial slices.

When we analyze the anterior and posterior of ST data, both using scRNA-seq allen_cortex_dwn.rds ?

Should we analyze adult mouse anterior ST data and posterior ST data using the same scRNA-seq data（ allen_cortex_dwn.rds &nbsp; ）?

best wishes!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarcElosua/SPOTlight"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月22日(星期五) 凌晨0:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MarcElosua/SPOTlight] residuals of the sum of squares doesn't work for Seurat object (Issue #101)





 
Hi @MirDom
 
Thank you very much for your interest in SPOTlight!
 
Your issue here is that you are trying to use the ggcells() function which is part of the scater package. This functino doesn't accept Seurat objects as an input, hence the error:
