### ISSUE TITLE
Error with NMF function when running spotlight_deconvolution

### ISSUE THREAD

**Issue by mvhunter1** [MarcElosua/SPOTlight#20]
Hi,

Thank you so much for developing this really interesting tool! I've been using it on some Visium datasets with mixed success. Sometimes spotlight_ls will run without any errors but sometimes it throws an error related to the NMF package/function: 

"Error: NMF::nmf - Input matrix x contains at least one null or NA-filled row."

This error seems to happen almost randomly, as sometimes spotlight_deconvolution will run without errors and sometimes it gives the error above, without me changing any of the inputs to the function. Any advice? I'm running R version 3.6.3 and SPOTlight version 0.1.4. Thank you!

**Comment by MarcElosua** [comment]
Hi @mvhunter1 ,
Thanks so much for using SPOTlight on your data! I believe this error is encountered when empty rows are passed to NMF. This can be due to one/some of the marker genes or variable features are all 0 in the count matrix. A most likely scenario is that the variable features are obtained and then the Seurat object is subsetted, therefore some of the variable features in the original object are all 0 after subsetting it.
Please let me know if that solves your issue,
Marc

**Comment by mvhunter1** [comment]
Hi Marc, thanks! I think I figured out the issue and it was basically what you said - I was using the "integrated" assay from a single-cell object where I'm assuming it contained NAs from genes that were present in one of the original objects but not the other. Using the SCT assay solves the problem as would I suppose subsetting the integrated object to include only genes present in both datasets. Thanks again!
