### ISSUE TITLE
Error: object 'count_mtrx' not found

### ISSUE THREAD

**Issue by ph329** [MarcElosua/SPOTlight#21]
Hi,

I'm getting the following error at the "Training...." step when trying to run spotlight_deconvolution when transf is set to either "sct" or "cpm": 

Error in NMF::nmf(x = count_mtrx, rank = k, seed = nmf_init, method = method) : 
  object 'count_mtrx' not found

It works perfectly with transf = "raw" or "uv" so the issue seems to be related to the transformation type itself. Any idea? Thanks!

**Comment by MarcElosua** [comment]
Hi @ph329,
Sorry for the delayed answer, and thanks for reporting this. I must have forgotten to change the description of the `transf` variable since SCT is no longer supported. You can do so with the raw command and passing the SCT@data slot instead of the raw counts slot. 
I will update this right away!
Thanks,
Marc
