### ISSUE TITLE
get_spatial_interaction_graph_fun.R

### ISSUE THREAD

**Issue by cadyyuheng** [MarcElosua/SPOTlight#29]
First, thanks for this fantastic tool! However, as I'm following the vignette, I have some issues understanding the calculation behind `get_spatial_interaction_graph_fun`

In particular, I didn't quite follow how the importance of the network is calculated by the algorithm. Besides, is there a reason why the row sum of `decon_mtrx` is not 1? Intuitively, since the row sum represents the sum of the composition of all possible cell types across one spot, the sum should be 1. I'd really appreciate any help~

**Comment by MarcElosua** [comment]
hi @cadyyuheng 

Thanks a lot for using SPOTlight and sorry for taking so long to reply.

The function `get_spatial_interaction_graph_fun` intends to be a visual representation of the  number of spots in which 2 cell types are found together. First it computes the number of times 2 cell types are co-localizing and then it scales the value between 0-1 for easier plotting.

With regards to the `decon_mtrx` not adding up to 1 that is due to the `min_cont` parameter. If set to 0 then all the rows will add up to 1 whilst if set to 0.03 for example it will remove all those cell types below that threshold.

Hope this helps!
