### ISSUE TITLE
Cell overabundance in deconvolution

### ISSUE THREAD

**Issue by wakelin-g** [MarcElosua/SPOTlight#30]
Greetings,

I have been trying to deconvolute my spatial data using a single-cell dataset of ours, however, for some reason a known cell-type is appearing to be much too abundant in the deconvoluted spots. When I look at a FeaturePlot of a gene specific for this cell type, there are only a few spots. If I set `min_cont` to a cutoff where the expression is more appropriate, it ends up cutting off another cell type of interest. 

Any ideas of what to do here? Could it be a problem with the resolution of my reference data set? The topic profile for this cell type is specific for only this cell type. Is this potentially noise caused by the LS method?

![image](https://user-images.githubusercontent.com/86983768/129782628-3b14d314-f657-4a18-bc08-0a559afb9340.png)

Any help would be appreciated as I've tried a few things to try and get around this and none have worked thus far.

Cheers,

Griffen

**Comment by MarcElosua** [comment]
hi @wakelin-g 

Thanks a lot for using SPOTlight and apologies for the late response!

In your case I would try 2 things that can help you get a sense of what may be going on.

1. I would look if all the cells from that cell types have a similar profile distribution and if so which genes are defining the topic profile for that cell type. You can take a look at how to do this in the section `0.6.2 Assess deconvolution` of the [vignette](https://marcelosua.github.io/SPOTlight/). We expect to see marker genes for that cell type being highly important and not shared across topics. If this is not the case two things can be happening:
     i) If you're seeing a lot of genes that are not necessarily of interest I would recommend removing the HVG and using a more curated marker gene list. This can be achieved by filtering the marker genes so those of interest are included in the model. This approach usually works well when we have very clearly defined cell types .
    ii) If you're seeing there are too few genes being used in the model then I would say to increase the flexibility of the marker gene filtering and adding some HVG  to add more features to the model.

2. Sometimes cell types are found at lower percentages due to them being smaller or because they are competing with another cell type that is overwhelming in that position - Tfh cells or FDC in the tonsil for example. In those cases I would check the distribution of the predicted proportions and set a reasonable threshold specific for each cell type.

lastly with regards to using individual marker genes to try to assess the location of a cell type I would not solely rely on 1 or 2 marker genes since the capture rate sensitivity can be very low for lowly-expressed/underrepresented genes. For visualizations purposes we have seen that carrying out gene denoising to recover the underlying structure of the data works quite well!

Hope this helps!
