### ISSUE TITLE
Mouse vs human gene symbols

### ISSUE THREAD

**Issue by astrid12345** [MarcElosua/SPOTlight#31]
Hello,

thank you for developing this helpful deconvolution tool! I was wondering in the function spotlight_deconvolution(), if it is already possible to use **mouse** SC data for deconvolving **human** ST data. The function now returns the error "Not enough genes in common between the single-cell and mixture dataset." which makes complete sense! The mouse gene symbols still have to be converted to uppercase.

As work-around I can find a human reference SC or convert rownames myself, but I was thinking more users might want to use reference sets from mouse/other species.

Thanks!

**Comment by MarcElosua** [comment]
Hi @astrid12345 

You got it spot on, the function returns not enough genes in common due to the differences in the gene symbols.
I haven't tried using mouse SC data to decompose human ST but there shouldn't be major issues besides some information being lost when converting genes to their homologous symbol.

If you have paired data from the same model/experiment I would suggest trying to convert the rownames before looking for a human reference.

I will think about making this an automatic thing but maybe its better that the user is aware and they have the option to change the names themselves so they can choose how to deal with 1:2 or 2:1 gene symbol mappings.

Thanks so much for the suggestion!

**Comment by astrid12345** [comment]
Hi MarcElosua,

Great! Thank you for the advice - I will take it into account. 
Yes, it's only a suggestion. I totally agree with you no matter when it's done (during SC pre-processing or as arguments in the function) the user should be aware and be able to choose how to deal with the gene symbol mappings.
