### ISSUE TITLE
Interpretation graph interaction and cell-cell correlation

### ISSUE THREAD

**Issue by WesDe** [MarcElosua/SPOTlight#34]
Hi,

Thank you again for your tools which provides some interesting features compared to other tools ! I had a naive question about graph interaction and cell-cell correlation. In your vignette we can see that some cell types have a strong interaction but a weak correlation (Astro - Oligo : -0.1). I might miss an important point but I thought that if cell types had a strong interaction they would have naturally a high correlation. Does the interaction graph is a count of interaction between cell types that can be biased by the number of spot containing the same mixing cell type?  Then the pearson correlation allows to remove this bias ? Could you help me to understand how to interpret both graph because I am confronted with the same result with my data please ? 

Best,
WesDe

**Comment by MarcElosua** [comment]
Hi @WesDe,

Thanks for your question it is very interesting and I can see where the confusion can come from. 
The graph interaction represents the total number of spots in which those 2 cell types are found. Therefore, two cell types that co-localize in space can either show a negative or positive correlation. As you mention, cell types that are found in many spots will likely have higher number of interactions just because they are more present. 

Hope this helps, 
Marc

**Comment by WesDe** [comment]
Hi @MarcElosua ,

Thanks for the clear answer !

WesDe
