### ISSUE TITLE
arguments explanation

### ISSUE THREAD

**Issue by giovp** [MarcElosua/SPOTlight#4]
Hi,

would it be possible to have a brief eplanation of ouple of arguments? 
- hvg. The default it's 0, what does it mean?
- ntop. It says that the default is't 100 in the docs, but then the actual default is NULL? See pic
![image](https://user-images.githubusercontent.com/25887487/90879031-96111680-e3a6-11ea-94a9-3cf5b1d4ff3d.png)

Thank you!

**Comment by MarcElosua** [comment]
Hi giovp,
Thanks so much for spotting this I'll change the Arg description right away to match the function (3000 and NUULL respectively).
I'm more than happy to comment on these arguments and any others you have doubts about.

- **hvg**: by default is 3.000. It refers to how many highly-variable genes to use along with the markers to train the model. As we show in the benchmarking process  [here](https://doi.org/10.1101/2020.06.03.131334) Figure 2 we see it is the optimal gene set to use.
- **ntop**: by default is NULL. It refers to how many marker genes to use when initializing the basis matrix. By setting it to NULL it will use all the marker genes for each cell type which returns optimal results in my experience!

Hope this solves your doubts, please don't hesitate to let me know if you have any more questions/clarifications!

**Comment by giovp** [comment]
Hi @MarcElosua ,

thanks a lot for the prompt reply! I had a look at the method section and I am still a bit confused. 
- So the final set of genes for the single cell data is: sc_genes = union(ntop_genes, hvg_genes) 
- And the final set of genes for the deconvolution is intersection(sc_genes, spatial_genes)

is that right?

**Comment by MarcElosua** [comment]
Exactly @giovp,

The gene_set used is the union between the marker genes and the HVG genes.
However, from these genes, we use those that intersect with the spatial dataset. This is due to the genes in the basis matrix needing to be in both the SC and the Spatial dataset. When running the deconvolution if there are genes in the basis matrix which are not present in the Spatial dataset it returns an error. Therefore we need to make sure we only use intersecting genes between them. When using good quality SC and Spatial data the genes removed should be minimal.

Hope the clarification makes sense

**Comment by giovp** [comment]
Amazing, thanks a lot !
