### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sailseem** [MarcElosua/SPOTlight#53]
Dear developer,

I know this install error has been reported, but I tried different ways to install, still did not work. Can you help me? I am using M1 chip MacBook and r version was 4.1

> install_github("https://github.com/MarcElosua/SPOTlight")
Downloading GitHub repo MarcElosua/SPOTlight@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: GenomeInf... (1.2.4 -> 1.2.7) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
✓  checking for file ‘/private/var/folders/by/2dc9qylx40d5f6kfx153psxw0000gn/T/Rtmpi0E0XM/remotes172144398a0c5/MarcElosua-SPOTlight-8f77e35/DESCRIPTION’ ...
─  preparing ‘SPOTlight’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SPOTlight_0.99.9.tar.gz’
   
Error: 5:1: unexpected input
4: 
5:  
   ^
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/by/2dc9qylx40d5f6kfx153psxw0000gn/T//Rtmpi0E0XM/file172145963082e/SPOTlight_0.99.9.tar.gz’ had non-zero exit status

Thanks a lot for your time

**Comment by MarcElosua** [comment]
Hi @sailseem 

Thank you so much for your interest in `SPOTlight`! I cannot gather much information from the error message you posted. However, `SPOTlight` has Bioconductor dependencies. Currently Bioconductor doesn't provide binaries for M1 processors since they compile them in Intel machines. My suggestion would be to install the intel R version ([R-4.1.3.pkg](https://cran.r-project.org/bin/macosx/base/R-4.1.3.pkg)) or try to install SPOTlight's dependencies from source using ARM compilers. Here are some threads with active discussions that can be helpful: 
> - https://support.bioconductor.org/p/9138121/
> - https://stackoverflow.com/questions/67680663/installing-specific-r-packages-from-source-with-apple-m1-chip-causing-repository
> - https://support.bioconductor.org/p/9137290/
> - https://www.reddit.com/r/bioinformatics/comments/qiqnzt/did_anyone_else_buy_a_m1_mac_and_realize/

Sorry for the inconvenience,
Marc
