### ISSUE TITLE
topic and cell type ?

### ISSUE THREAD

**Issue by caiquanyou** [MarcElosua/SPOTlight#6]
what is the different meaning about topic and cell type?
could not understand why use NNLS lastly to solve Q  and  P since last step have solved the ST data propotion?

**Comment by MarcElosua** [comment]
Hi @caiquanyou, 

The NNLS in the last step is necessary to solve Q and P since the topics may not necessarily be specific for a cell type. Similar cell types or states could have partially overlapping topic profiles which would make the 1:1 topic:cell-type relation not true. An example can be seen in SPOTlights tutorial when we show the topic profiles specificity for each cell type [here](https://github.com/MarcElosua/SPOTlight/blob/master/man/figures/README-unnamed-chunk-22-1.png). There we observe how each cell type has a specific topic profile except for _L5IT_ and _Serpinf1_ which have partial topic profiles. 

Hope this can solve your question but please do not hesitate to reach out if it wasn't clear!
Marc

**Comment by caiquanyou** [comment]
Thanks!I got it
