### ISSUE TITLE
Error: Couldn't extract image coordinates

### ISSUE THREAD

**Issue by sokratiag** [MarcElosua/SPOTlight#60]
Hi,

I am trying to use spotlight on ST dataset (not 10x visium but the old protocol) but I get the following error:

Error in .extract_counts(y, assay_sp, slot_sp) : 
  Couldn't extract image coordinates.
            Please check class(x) is SpatialExperiment, Seurat,
            dataframe or matrix
In addition: Warning message:
In .set_groups_if_null(x) : Grouping cells into celltypes by Idents(x)

ST data is read as a dataframe:  st_count = data.frame(fread("path"),check.names=F)

spotlight_ls <- trainNMF(
  sc,
  st_count,
  mgs = cluster_markers_all, # Dataframe with the marker genes
  hvg = 500,
  ntop = NULL,
  weight_id = "avg_log2FC",
  group_id = "cluster",
  gene_id = "gene"
)
Isn't it possible to run it without giving the image coordinates? 

Thanks!

**Comment by MarcElosua** [comment]
hi @sokratiag 

Thank you for your interest on SPOTlight. 

As you can see in the documentation of the parameters x and y represent the single-cell and mixture dataset, respectively. Can be a numeric matrix, SingleCellExperiment or SeuratObjecy. Therefore, I would suggest to convert st_count to a matrix format and it shouldn't return any errors

Sorry for the confusing error message, it was a copy-paste mistake and should now be fixed in the main branch on GitHub. 

Please let me know if you encounter any further issues!

**Comment by sokratiag** [comment]
hi @MarcElosua 

Thanks a lot for your help - I converted the data frame to a matrix and problem solved!
