### ISSUE TITLE
Issue plotSpatialScatterpie with a seurat object

### ISSUE THREAD

**Issue by JulioLeonIncio** [MarcElosua/SPOTlight#64]
Hello, 
 I am trying to plot a scatterpie having a seurat object as X and a matrix with deconvoluted spots in Y. I keep getting this error:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/23158173/177899305-bb35a2af-a6ad-429d-8d64-4ae90da8ead5.png">

any help?

Thank you!

Julio

**Comment by MarcElosua** [comment]
Hi @JulioLeonIncio,

It seems like the number of spots in your Seurat object and the number of spots in your deconvolution matrix aren't the same. Can you check that they match and that they have the same names? This could be due to there being multiple images in your seurat object. You can also try passing to x the spot coordinates for the image you're trying to visualize. You can extract the coordinates as follows:

```
x <- as.matrix(SeuratObject::GetTissueCoordinates(se_obj, image = slice))
```
Hope this helps! Let me know if you have any further issues!

**Comment by JulioLeonIncio** [comment]
It worked well after matching the spot barcodes from the matrix and image coordinates. Yeah, I had eight merged images in my Seurat object.

Thank you!
