### ISSUE TITLE
Spots are shifted from the image

### ISSUE THREAD

**Issue by onahman** [MarcElosua/SPOTlight#9]
Hi,
I tried to use SPOTlight::spatial_scatterpie on my data and the spots had a shift from the image.
After probing the code I found the reason why:

  ## Plot spatial scatterpie plot
  scatterpie_plt <- suppressMessages(ggplot2::ggplot() +
                                       ggplot2::annotation_custom(grob = img_grob,
                                                                  xmin = 0,
                                                                  xmax = 600,
                                                                  ymin = 0,
                                                                  ymax = -600) +
                                       scatterpie::geom_scatterpie(data = spatial_coord,
                                                                   aes(x = imagecol_scaled,
                                                                       y = imagerow_scaled),
                                                                   cols = cell_types_all,
                                                                   color = NA,
                                                                   alpha = scatterpie_alpha,
                                                                   pie_scale = pie_scale) +
                                       ggplot2::scale_y_reverse() +
                                       ggplot2::ylim(600, 0) +
                                       ggplot2::xlim(0, 600) +
                                       cowplot::theme_half_open(11, rel_small = 1) +
                                       ggplot2::theme_void() +
                                       ggplot2::coord_fixed(ratio = 1,
                                                            xlim = NULL,
                                                            ylim = NULL,
                                                            expand = TRUE,
                                                            clip = "on"))

The hard coding here of -600 and 600 instead of using the image dimensions like this:
 xmax = ncol(img) and  ymax = -nrow(img).

**Comment by MarcElosua** [comment]
Thanks a lot for pointing this out @onahman,
I have updated the function and should be fully functional!

**Comment by microbiomeCat** [comment]
Hi, I have try the  SPOTlight::spatial_scatterpie on my data too, However, I found all the spots were all located at the top left corner. Then I looked at the nrow(img) or ncol(img), it's about 15000, but the spatial_coord$imagecol_scaled or   spatial_coord$imagerow_scaled is about 20 to 550. I am not sure，but I think this correlation maybe not needed, since here the  spatial_coord$imagecol and  spatial_coord$imagerow  were not  used.  I guess if we use  xmax = ncol(img) and ymax = -nrow(img), then the (x,y) of the spots should not be scaled.  @MarcElosua @onahman

**Comment by morganee261** [comment]
Hello @MarcElosua, I am also experiencing the same issue, on some of my samples the spots are shifted from the image. I am using SPOTlight 0.1.7. Would you be able to help ?
thanks for this nice package
morgane

**Comment by MarcElosua** [comment]
Hi @microbiomeCat & @morganee261,

Sorry to hear that this is happening, the implementation @onahman proposed was already in place in version 0.1.7. Are you using the same image path you used to build the spatial Seurat object? Sometimes there may be issues if you used highres and lowres for the other since the pixels and scaling factors don't match
